# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: swipe.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'swipe.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bswipe.proto\x12\x0e\x63om.pulse.grpc\"V\n\x0cSwipeRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\x12\x11\n\ttarget_id\x18\x02 \x01(\t\x12\x0f\n\x07is_like\x18\x03 \x01(\x08\x12\x11\n\ttimestamp\x18\x04 \x01(\x03\"1\n\rSwipeResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2T\n\x0cSwipeService\x12\x44\n\x05Swipe\x12\x1c.com.pulse.grpc.SwipeRequest\x1a\x1d.com.pulse.grpc.SwipeResponseB\x02P\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'swipe_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'P\001'
  _globals['_SWIPEREQUEST']._serialized_start=31
  _globals['_SWIPEREQUEST']._serialized_end=117
  _globals['_SWIPERESPONSE']._serialized_start=119
  _globals['_SWIPERESPONSE']._serialized_end=168
  _globals['_SWIPESERVICE']._serialized_start=170
  _globals['_SWIPESERVICE']._serialized_end=254
# @@protoc_insertion_point(module_scope)
