# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import swipe_pb2 as swipe__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in swipe_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SwipeServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Swipe = channel.unary_unary(
                '/com.pulse.grpc.SwipeService/Swipe',
                request_serializer=swipe__pb2.SwipeRequest.SerializeToString,
                response_deserializer=swipe__pb2.SwipeResponse.FromString,
                _registered_method=True)


class SwipeServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Swipe(self, request, context):
        """The function our Server will expose
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SwipeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Swipe': grpc.unary_unary_rpc_method_handler(
                    servicer.Swipe,
                    request_deserializer=swipe__pb2.SwipeRequest.FromString,
                    response_serializer=swipe__pb2.SwipeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'com.pulse.grpc.SwipeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('com.pulse.grpc.SwipeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SwipeService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Swipe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/com.pulse.grpc.SwipeService/Swipe',
            swipe__pb2.SwipeRequest.SerializeToString,
            swipe__pb2.SwipeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
